/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui.DB;

import com.vehicle.DB.Dbaccess;
import com.vehicle.DB.Dbconnect;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanjeewa
 */
public class category extends javax.swing.JFrame {

    /**
     * Creates new form category
     */
    public category() {
        initComponents();
        txtcid.setText("");
        txtcname.setText("");
        jDateChooser1.setDate(null);
        txtcolor.setText("");
        
        
        try {
            Connection c=Dbconnect.getconnection();
            Statement s=(Statement) c.createStatement();
            ResultSet rs=s.executeQuery("SELECT * FROM supplier");
            Vector v=new  Vector();
            Vector v1 =new Vector();
            Vector v2 =new Vector();
            while(rs.next()){
                
                v.add(rs.getString("sname"));
                v1.add(rs.getString("sprice"));
                v2.add(rs.getString("sdiscount"));
            
            }
            ccompany.setModel(new DefaultComboBoxModel(v));
            cprice.setModel(new DefaultComboBoxModel(v1));
            cdiscount.setModel(new DefaultComboBoxModel(v2));
            
                    
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
        
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtcid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtcname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ccompany = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcolor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cprice = new javax.swing.JComboBox<>();
        cdiscount = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblimg = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 255, 255))); // NOI18N

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanjeewa\\Desktop\\st-images\\1458923755_edit-delete.png")); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanjeewa\\Desktop\\st-images\\1458923365_vector_66_12.png")); // NOI18N
        jButton3.setText("Save Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanjeewa\\Desktop\\st-images\\1458923639_search_magnifying_glass_find.png")); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanjeewa\\Desktop\\st-images\\1458923466_interact.png")); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 255, 255))); // NOI18N

        txtcid.setText("jTextField1");

        jLabel1.setText("Category ID");

        txtcname.setText("jTextField2");

        jLabel2.setText("Category Name");

        ccompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose.." }));
        ccompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccompanyActionPerformed(evt);
            }
        });

        jLabel3.setText("Supplier ID");

        jLabel5.setText("Year");

        jLabel6.setText("Colour");

        txtcolor.setText("jTextField1");

        jLabel7.setText("Price");

        jLabel8.setText("Discount");

        cprice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpriceActionPerformed(evt);
            }
        });

        cdiscount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cdiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdiscountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcolor, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(cdiscount, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cprice, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(75, 75, 75))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(123, 123, 123)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(ccompany, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcid)
                            .addComponent(txtcname))))
                .addGap(113, 113, 113))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ccompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cprice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 255, 255))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Category ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Image"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblimg, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanjeewa\\Desktop\\st-images\\1458925816_image_add.png")); // NOI18N
        jButton6.setText("Add Image");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jButton6)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  // TODO add your handling code here:
        
        Connection c;
        try {
            
             File f=jFileChooser1.getSelectedFile();
            String path=f.getAbsolutePath();
            path =path.replace("\\","/");
            
            
            
           c = Dbconnect.getconnection();
           Statement s=c.createStatement();
           
         // Dbaccess da=new Dbaccess();
           
          ResultSet rs=s.executeQuery("SELECT * FROM category WHERE cid='"+txtcid.getText()+"'");
       // String q="SELECT * FROM category WHERE cid='"+txtcid.getText()+"'";
           // da.getData(q);
               SimpleDateFormat date1=new SimpleDateFormat("yyyy-MM-dd");  
          byte[] image = null;
        
            
//            
            while(rs.next()){
            
             
            txtcid.setText(rs.getString("cid"));
            txtcname.setText(rs.getString("cname"));
           
             ccompany.setSelectedItem(rs.getString("ccompany"));
            jDateChooser1.setDate(date1.parse(rs.getString("cyear")));
             txtcolor.setText(rs.getString("ccolor"));
              cprice.setSelectedItem(rs.getString("cprice"));
               cdiscount.setSelectedItem(rs.getString("cdiscount"));
          image = rs.getBytes("cpicture");
        
            }
            
   


//              Image img = Toolkit.getDefaultToolkit().createImage(image);
//             ImageIcon icon = new ImageIcon(img);
          //    lblimg.setIcon(icon);
           
     // File f1=new File(lblimg.getText().toString());
        
        
//        Image im=ImageIO.read(f1);
//        im=im.getScaledInstance(lblimg.getWidth(),lblimg.getHeight(),Image.SCALE_SMOOTH);
//        lblimg.setIcon(new ImageIcon(im));


//                Blob imageBlob = rs.getBlob("cpicture");
//         InputStream binaryStream = imageBlob.getBinaryStream(0, imageBlob.length());
//           lblimg.setIcon((Icon) binaryStream);

               

            
            
            Blob imageBlob = rs.getBlob("cpicture");
InputStream binaryStream = imageBlob.getBinaryStream(0, imageBlob.length());
           // byte[] imageBytes = imageBlob.getBytes(1, (int) imageBlob.length());
            
            lblimg.setIcon((Icon) binaryStream);
            
            
            
            
            
        } catch (ClassNotFoundException | SQLException | ParseException ex) {
            Logger.getLogger(category.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
        
        
        
        
        
        String q="SELECT * FROM category WHERE cid='"+txtcid.getText()+"'";
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        
        
       // Connection     c;
       
   

               int x=JOptionPane.showConfirmDialog(rootPane,"do you want to save this record?");
            
            if(x==0){
            
                
                File f=jFileChooser1.getSelectedFile();
        String path=f.getAbsolutePath();
        path =path.replace("\\","/");
       File f1=new File(path);
        
           
       SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault());
     //  String date=sdf.format(jDateChooser1.getDate());
      
           
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                String id=txtcid.getText();
                String name=txtcname.getText();
                String company=ccompany.getSelectedItem().toString();
                    SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd");  
                 String year=date.format(jDateChooser1.getDate());
                String color=txtcname.getText();
                String price=cprice.getSelectedItem().toString();
            String discount=cdiscount.getSelectedItem().toString();
            
            
      /*      
            c = Dbconnect.getconnection();
            
            java.sql.Statement s=c.createStatement();
           
            s.executeUpdate("INSERT INTO category VALUES ('"+txtcid.getText()+"','"+txtcname.getText()+"','"+ccompany.getSelectedItem().toString()+"','"+date+"','"+txtcolor.getText()+"','"+cprice.getSelectedItem().toString()+"','"+cdiscount.getSelectedItem().toString()+"','"+path+"')");
               s.executeUpdate("INSERT INTO category('cid','cname','ccompany','cyear','ccolor','cprice','cdiscount','cpicture') VALUES ('"+txtcname.getText()+"','"+ccompany.getSelectedItem().toString()+"','"+date+"','"+txtcolor.getText()+"','"+cprice.getSelectedItem().toString()+"','"+cdiscount.getSelectedItem().toString()+"','"+path+"')");
            
               s.executeUpdate("INSERT INTO `vehicleservice`.`category` (`cname`, `ccompany`, `cyear`, `ccolor`, `cprice`, `cdiscount`, `cpicture`) VALUES ( '"+name+"', '"+company+"', '"+year+"', '"+color+"', '"+price+"', '"+discount+"', '"+path+"');");
               
                  s.executeUpdate("INSERT INTO `vehicleservice`.`category` (`cname`, `ccompany`, `cyear`, `ccolor`, `cprice`, `cdiscount`, `cpicture`) VALUES ( '"+name+"', '"+company+"', '"+year+"', '"+color+"', '"+price+"', '"+discount+"', '"+path+"');");
                
                */
      
      
      
                 String q= "INSERT INTO `vehicleservice`.`category` (`cname`,`ccompany`, `cyear`, `ccolor`, `cprice`, `cdiscount`, `cpicture`) VALUES ( '"+name+"', '"+company+"', '"+year+"', '"+color+"', '"+price+"', '"+discount+"', '"+path+"');";
                 
                 
                 Dbaccess da=new Dbaccess();
                 
                 da.insertData(q);
                 
                  
         txtcid.setText("");
        txtcname.setText("");
        jDateChooser1.setDate(null);
       // txtsupplier.setText("");
          ccompany.setSelectedIndex(0);  
          cprice.setSelectedItem(0);
            lblimg.setIcon(null);
        
        
        }
            
            
            
       
           
       
     
               
        
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String id = txtcid.getText();
        String name = txtcname.getText();
        String company = ccompany.getSelectedItem().toString();
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        String year = date.format(jDateChooser1.getDate());
        String color = txtcname.getText();
        String price = cprice.getSelectedItem().toString();
        String discount = cdiscount.getSelectedItem().toString();

        
        
        try {
//        Connection c=Dbconnect.getconnection();
//         Statement s=c.createStatement();
//       
//         s.executeUpdate("UPDATE category SET cname='"+txtcname.getText()+"',ccompany='"+ccompany.getSelectedItem().toString()+"'  WHERE cid='"+txtcid.getText()+"' ");
//         
         Dbaccess da=new Dbaccess();
      

         String q="UPDATE `vehicleservice`.`category` SET `cid`='"+id+"', `cname`='"+name+"', `ccompany`='"+company+"',"
                 + "`cyear`='"+year+"', `ccolor`='"+color+"', `cprice`='"+price+"', "
                 + "`cdiscount`='"+discount+"', `cpicture`='' WHERE (`cid`='"+id+"');";
         
         da.insertData(q);
         
         
    } catch (Exception e) {
        e.printStackTrace();
    }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
        try {
        Connection c=Dbconnect.getconnection();
       Statement s=c.createStatement();
         
       
         
         
        ResultSet rs=s.executeQuery("SELECT * FROM category WHERE cid='"+txtcid.getText()+"'");
        //ResultSet r=s.executeUpdate("DELETE FROM categories WHERE pid='"+txtcid.getText()+"'");
        String x=txtcid.getText();
        int y=Integer.parseInt(x);
        while(rs.next()){
            if(y!=1){
           s.executeUpdate("DELETE FROM category WHERE cid='"+txtcid.getText()+"'"); 
        JOptionPane.showMessageDialog(rootPane,"successfuly delete");
        
            }else
            {
                JOptionPane.showMessageDialog(rootPane, "cant delete");
            
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
        
        
        
        
        
        Dbaccess da=new Dbaccess();
        String q="";
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ccompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccompanyActionPerformed

    private void cpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpriceActionPerformed

    private void cdiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdiscountActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        try {
        jFileChooser1.showOpenDialog(this);
        File f=jFileChooser1.getSelectedFile();
        String path=f.getAbsolutePath();
        path =path.replace("\\","/");
        File f1=new File(path);
        
        
        Image im=ImageIO.read(f1);
        im=im.getScaledInstance(lblimg.getWidth(),lblimg.getHeight(),Image.SCALE_SMOOTH);
        lblimg.setIcon(new ImageIcon(im));
               
    
        
    } catch (Exception e) {
        e.printStackTrace();
    }
           
        
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new category().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ccompany;
    private javax.swing.JComboBox<String> cdiscount;
    private javax.swing.JComboBox<String> cprice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblimg;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtcname;
    private javax.swing.JTextField txtcolor;
    // End of variables declaration//GEN-END:variables
}
