/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui.DB;



 import java.io.ByteArrayInputStream;
import com.vehicle.DB.Dbaccess;
import com.vehicle.DB.Dbconnect;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;















/**
 *
 * @author Sanjeewa
 */
public class categories extends javax.swing.JInternalFrame {

    /**
     * Creates new form categories
     */
    public categories() {
        initComponents();
//             try {
//            Connection c=Dbconnect.getconnection();
//            Statement s=(Statement) c.createStatement();
//            ResultSet rs=s.executeQuery("SELECT * FROM supplier");
//            Vector v=new  Vector();
//            Vector v1 =new Vector();
//            Vector v2 =new Vector();
//            while(rs.next()){
//                
//                v.add(rs.getString("sname"));
//                v1.add(rs.getString("sprice"));
//                v2.add(rs.getString("sdiscount"));
//            
//            }
//            ccompany.setModel(new DefaultComboBoxModel(v));
//            cprice.setModel(new DefaultComboBoxModel(v1));
//            cdiscount.setModel(new DefaultComboBoxModel(v2));
//            
//                    
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
        
        
       clear();
        tableload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser2 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcolor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblid = new javax.swing.JLabel();
        cdiscount = new javax.swing.JComboBox<>();
        ccompany = new javax.swing.JComboBox<>();
        txtprice = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lblimg = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 255, 255))); // NOI18N

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanjeewa\\Desktop\\st-images\\1458923755_edit-delete.png")); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanjeewa\\Desktop\\st-images\\1458923365_vector_66_12.png")); // NOI18N
        jButton3.setText("Save Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanjeewa\\Desktop\\st-images\\1458923466_interact.png")); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/java/1459615138_edit-clear.png"))); // NOI18N
        jButton7.setText("clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 255, 255))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Category ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(685, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 255, 255))); // NOI18N

        jLabel1.setText("Category ID");

        txtcname.setText("jTextField2");

        jLabel2.setText("Category Name");

        jLabel3.setText("Supplier ID");

        jLabel5.setText("Year");

        jLabel6.setText("Colour");

        jLabel7.setText("Price");

        jLabel8.setText("Discount");

        lblid.setText("ID");

        cdiscount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "2%", "3%", "4%", "5%" }));

        ccompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "bmw", "audi", "toyota", "benz", "volvo" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtprice)
                            .addComponent(txtcolor)
                            .addComponent(cdiscount, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(75, 75, 75))
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(112, 112, 112)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblid))
                            .addComponent(txtcname)
                            .addComponent(ccompany, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblid))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ccompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Image"));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblimg, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lblimg, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanjeewa\\Desktop\\st-images\\1458925816_image_add.png")); // NOI18N
        jButton6.setText("Add Image");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanjeewa\\Desktop\\st-images\\1458923639_search_magnifying_glass_find.png")); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton6)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void tableload(){
    
    
        try {
            String q= "SELECT *FROM category";
            
            Dbaccess da=new Dbaccess();
            
            jTable1.setModel(DbUtils.resultSetToTableModel( da.getData(q)));
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(vehicledetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(vehicledetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    
    }
    
    
    
    
     public void clear(){
    
    
         lblid.setText("");
         txtsearch.setText("");
         txtcname.setText("");
         txtcolor.setText("");
         jDateChooser1.setDate(null);
         ccompany.setSelectedItem(null);
         
         cdiscount.setSelectedItem(null);
         lblimg.setIcon(null);
         lblimg.setText("");
         txtprice.setText("");
      
    }
    
     public void clear1(){
    
    
         lblid.setText("");
         txtsearch.setText("");
         txtcname.setText("");
         txtcolor.setText("");
         jDateChooser1.setDate(null);
         txtprice.setText("");
         //ccompany.setSelectedItem(0);
         //cprice.setSelectedItem(0);
         //cdiscount.setSelectedItem(0);
         lblimg.setIcon(null);
      
    }
    
    
    
    
    
    
    
    
    
    
    
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        try {
            jFileChooser2.showOpenDialog(this);
            File f=jFileChooser2.getSelectedFile();
            String path=f.getAbsolutePath();
            path =path.replace("\\","/");
                File f1=new File(path);

                Image im=ImageIO.read(f1);
                im=im.getScaledInstance(lblimg.getWidth(),lblimg.getHeight(),Image.SCALE_SMOOTH);
                lblimg.setIcon(new ImageIcon(im));

            } catch (Exception e) {
                e.printStackTrace();
            }
//





    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
//
//        try {
//            Connection c=Dbconnect.getconnection();
//            Statement s=c.createStatement();
//
//            ResultSet rs=s.executeQuery("SELECT * FROM category WHERE cid='"+txtcid.getText()+"'");
//            //ResultSet r=s.executeUpdate("DELETE FROM categories WHERE pid='"+txtcid.getText()+"'");
//            String x=txtcid.getText();
//            int y=Integer.parseInt(x);
//            while(rs.next()){
//                if(y!=1){
//                    s.executeUpdate("DELETE FROM category WHERE cid='"+txtcid.getText()+"'");
//                    JOptionPane.showMessageDialog(rootPane,"successfuly delete");
//
//                }else
//                {
//                    JOptionPane.showMessageDialog(rootPane, "cant delete");
//
//                }
//                
//                
//                
//                tableload();
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//
//        Dbaccess da=new Dbaccess();
//        String q="";


 int x=JOptionPane.showConfirmDialog(rootPane,"Do you want to delete");
        
        if(x==0){
        
  String id=txtsearch.getText();
        String ids=lblid.getText();
        
        
        String q="DELETE FROM category WHERE cid='"+ids+"' ";
        
        
        Dbaccess da=new Dbaccess();
        
        da.insertData(q);
        
        tableload();
        
            clear();
        }






    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        // Connection     c;

        int x=JOptionPane.showConfirmDialog(rootPane,"do you want to save this record?");

        if(x==0){

            File f=jFileChooser2.getSelectedFile();
            String path=f.getAbsolutePath();
            path =path.replace("\\","/");
                // File f1=new File(path);

                SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault());
                //  String date=sdf.format(jDateChooser1.getDate());

                String id=txtsearch.getText();
                String name=txtcname.getText();
                String company=ccompany.getSelectedItem().toString();
                SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd");
                String year=date.format(jDateChooser1.getDate());
                String color=txtcolor.getText();
            //    String price=cprice.getSelectedItem().toString();
            String price=txtprice.getText();
                String discount=cdiscount.getSelectedItem().toString();

                /*
                c = Dbconnect.getconnection();

                java.sql.Statement s=c.createStatement();

                s.executeUpdate("INSERT INTO category VALUES ('"+txtcid.getText()+"','"+txtcname.getText()+"','"+ccompany.getSelectedItem().toString()+"','"+date+"','"+txtcolor.getText()+"','"+cprice.getSelectedItem().toString()+"','"+cdiscount.getSelectedItem().toString()+"','"+path+"')");
                s.executeUpdate("INSERT INTO category('cid','cname','ccompany','cyear','ccolor','cprice','cdiscount','cpicture') VALUES ('"+txtcname.getText()+"','"+ccompany.getSelectedItem().toString()+"','"+date+"','"+txtcolor.getText()+"','"+cprice.getSelectedItem().toString()+"','"+cdiscount.getSelectedItem().toString()+"','"+path+"')");

                s.executeUpdate("INSERT INTO `vehicleservice`.`category` (`cname`, `ccompany`, `cyear`, `ccolor`, `cprice`, `cdiscount`, `cpicture`) VALUES ( '"+name+"', '"+company+"', '"+year+"', '"+color+"', '"+price+"', '"+discount+"', '"+path+"');");

                s.executeUpdate("INSERT INTO `vehicleservice`.`category` (`cname`, `ccompany`, `cyear`, `ccolor`, `cprice`, `cdiscount`, `cpicture`) VALUES ( '"+name+"', '"+company+"', '"+year+"', '"+color+"', '"+price+"', '"+discount+"', '"+path+"');");

                */

                String q= "INSERT INTO `vehicleservice`.`category` (`cname`,`ccompany`, `cyear`, `ccolor`, `cprice`, `cdiscount`, `cpicture`) VALUES ( '"+name+"', '"+company+"', '"+year+"', '"+color+"', '"+price+"', '"+discount+"', '"+path+"');";

                Dbaccess da=new Dbaccess();

                da.insertData(q);

//                txtcid.setText("");
//                txtcname.setText("");
//                jDateChooser1.setDate(null);
//                // txtsupplier.setText("");
//                ccompany.setSelectedIndex(0);
//                cprice.setSelectedItem(0);
//                lblimg.setIcon(null);


            clear();

            }
        
        
        
        tableload();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        
        
       // clear();
//           
//        try {
//            
//             String search=txtsearch.getText();
//            
//            String q="SELECT * FROM category WHERE cname like '%"+search+"%' ";
//            Dbaccess da=new Dbaccess();
//            
//            
//            
//           
//          
//            jTable1.setModel(DbUtils.resultSetToTableModel( da.getData(q)));
//            
//            
//            
//            
//            
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(vehicledetails.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(vehicledetails.class.getName()).log(Level.SEVERE, null, ex);
//        }


String search=txtsearch.getText();
            
            String q="SELECT * FROM category WHERE cname like '%"+search+"%' ";
            Dbaccess da=new Dbaccess(); 
            
            
            
           
          
        try {
            jTable1.setModel(DbUtils.resultSetToTableModel( da.getData(q)));
            
            
            
//        Connection c;
//        try {
//
//
//
//
//            c = Dbconnect.getconnection();
//            Statement s=c.createStatement();
//
//            // Dbaccess da=new Dbaccess();
//
//            ResultSet rs=s.executeQuery("SELECT * FROM category WHERE cid='"+txtcid.getText()+"'");
//            // String q="SELECT * FROM category WHERE cid='"+txtcid.getText()+"'";
//            // da.getData(q);
//
//      
//            SimpleDateFormat date1=new SimpleDateFormat("yyyy-MM-dd");
//
//
//            //
//            while(rs.next()){
//                lbl
//                txtcid.setText(rs.getString("cid"));
//                txtcname.setText(rs.getString("cname"));
//               
//                ccompany.setSelectedItem(rs.getString("ccompany"));
//                jDateChooser1.setDate(date1.parse(rs.getString("cyear")));
//                 txtcolor.setText(rs.getString("ccolor"));
//               // cprice.setSelectedItem(rs.getString("cprice"));
//                 txtprice.setText("cprice");
//                cdiscount.setSelectedItem(rs.getString("cdiscount"));
//                lblimg.setText(rs.getString("image"));
//              //  image = rs.getBytes("cpicture");
//            }
//
////            Image img = Toolkit.getDefaultToolkit().createImage(image);
////            ImageIcon icon = new ImageIcon(img);
////           // lblimg.setIcon(icon);
////
////               File f1=new File(lblimg.getText().toString());
////
////                    Image im=ImageIO.read(f1);
////               im=im.getScaledInstance(lblimg.getWidth(),lblimg.getHeight(),Image.SCALE_SMOOTH);
////                   lblimg.setIcon(new ImageIcon(im));
//
//
//
//
//            
//            tableload();
//
//            
//        } catch (ClassNotFoundException | SQLException | ParseException ex) {
//            Logger.getLogger(category.class.getName()).log(Level.SEVERE, null, ex);
//
//        } 
////catch (IOException ex) {
////            Logger.getLogger(categories.class.getName()).log(Level.SEVERE, null, ex);
////        }
//
//        String q="SELECT * FROM category WHERE cid='"+txtcid.getText()+"'";
//
//





//clear();
//           
//        try {
//            
//             String search=txtcid.getText();
//            
//            String q1="SELECT * FROM category WHERE cname like '"+search+"' ";
//            Dbaccess da=new Dbaccess();
//
//
//
//
//          
//            jTable1.setModel(DbUtils.resultSetToTableModel( da.getData(q1)));
//
//
//
//
//            
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(vehicledetails.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(vehicledetails.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//
//
//
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(categories.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(categories.class.getName()).log(Level.SEVERE, null, ex);
        }







        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String id=lblid.getText();
        String name=txtcname.getText();
        String company=ccompany.getSelectedItem().toString();
        SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd");
        String year=date.format(jDateChooser1.getDate());
        String color=txtcolor.getText();
       // String price=cprice.getSelectedItem().toString();
      String price=txtprice.getText();
     String discount=cdiscount.getSelectedItem().toString();
        
   /////  String img =lblimg.getText();
   //     System.out.println(img);
 //Icon path1= lblimg.getIcon();
   //  Image image = ImageIO.read(new File("images/c.jpg"));  
          
//// ImageIcon path = new ImageIcon(img);
 

          File f=jFileChooser2.getSelectedFile();
           String path=f.getAbsolutePath();
           path =path.replace("\\","/");

        try {
            //        Connection c=Dbconnect.getconnection();
            //         Statement s=c.createStatement();
            //
            //         s.executeUpdate("UPDATE category SET cname='"+txtcname.getText()+"',ccompany='"+ccompany.getSelectedItem().toString()+"'  WHERE cid='"+txtcid.getText()+"' ");
            //
            Dbaccess da=new Dbaccess();

            String q="UPDATE `vehicleservice`.`category` SET `cid`='"+id+"', `cname`='"+name+"', "
                    + "`ccompany`='"+company+"',"+ "`cyear`='"+year+"', `ccolor`='"+color+"', "
                    + "`cprice`='"+price+"', "+ "`cdiscount`='"+discount+"', `cpicture`='"+path+"' WHERE (`cid`='"+id+"');";
            
            
            
            
            
            
            
            
            
            
 //String q="UPDATE `vehicleservice`.`category` SET `cid`='"+id+"', `cname`='"+name+"', `ccompany`='"+company+"',`cyear`='"+year+"', `ccolor`='"+color+"', `cprice`='"+price+"', `cdiscount`='"+discount+"', `cpicture`='"+path+"' WHERE (`cid`='"+id+"');";
//            String q="UPDATE category SET cname='"+name+"',ccompany='"+company+"',"
//                    + "cyear='"+year+"',ccolor='"+color+"',cprice='"+price+"',"
//                    + "cdiscount='"+discount+"',cpicture='"+path+"' WHERE (cid='"+id+"');";
            
            
            
            da.insertData(q);
            tableload();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:


 //Tabel click event
 
        int r=jTable1.getSelectedRow();
        
        
        String id=jTable1.getValueAt(r,0).toString();
        String name=jTable1.getValueAt(r, 1).toString();
        String  company=jTable1.getValueAt(r, 2).toString();
        String year=jTable1.getValueAt(r, 3).toString();
        String color=jTable1.getValueAt(r, 4).toString();
        String price=jTable1.getValueAt(r, 5).toString();
        String discount=jTable1.getValueAt(r,6).toString();
        String image=jTable1.getValueAt(r,7).toString();
        
        
//        txtvid.setText(id);
    lblid.setText(id);
        //txtcid.setText(model);
        txtcname.setText(name);
        ccompany.setSelectedItem(company);
            DateFormat format = new SimpleDateFormat("yyyy-MM-dd");  
        try {
            jDateChooser1.setDate(format.parse(year));
        } catch (ParseException ex) {
            Logger.getLogger(vehicledetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         txtcolor.setText(color);
        //cprice.setSelectedItem(price);
        txtprice.setText(price);
        cdiscount.setSelectedItem(discount);
         
        
        
        
        
        //get the image from the db
        String sql="SELECT cid,cpicture FROM category WHERE  cid = '"+jTable1.getValueAt(r,0).toString()+"' ;";  
        
        try {
            Connection conn = Dbconnect.getconnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rst = pst.executeQuery();
//            Blob imageBlob = null ;
              while(rst.next()){
//                    imageBlob = rst.getBlob("cpicture");
//                    System.out.println(imageBlob);


lblimg.setText(rst.getString("cpicture"));

              } 
              
              
              
              
               File f1=new File(lblimg.getText().toString());
        
        
        Image im=ImageIO.read(f1);
        im=im.getScaledInstance(lblimg.getWidth(),lblimg.getHeight(),Image.SCALE_SMOOTH);
       lblimg.setIcon(new ImageIcon(im));
               
              
              //get the image for the DB
//            InputStream binaryStream = imageBlob.getBinaryStream(0, imageBlob.length());
////           InputStream binaryStream = imageBlob.getBinaryStream(0, imageBlob.length());
//            lblimg.setIcon((Icon) binaryStream);  

            
            
//            	InputStream in = rst.getBinaryStream(1);
//				OutputStream f = new FileOutputStream(new File(""));
               
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(categories.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(categories.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(categories.class.getName()).log(Level.SEVERE, null, ex);
        } 
                           
                           
        
            
               
                   
                
                
                
      
        

           
                           
                           
                           
          

  

          //     File f1=new File(lblimg.getText().toString());
                
                
                
        
        //    lblimg.setText("cpicture");
  
            
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        clear();
        txtsearch.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ccompany;
    private javax.swing.JComboBox<String> cdiscount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblimg;
    private javax.swing.JTextField txtcname;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
